### ISSUE TITLE
RFC - Remove Environment Checker From Language Limbo

### ISSUE THREAD

**Issue by dyslexicsteak** [unified-naming-convention/NamingStandard#25]
- Feature Name: standardise_environment_checker
- Start Date: 2022-9-10

# Summary
[summary]: #summary

Standardise `UNCCheckEnv.lua` to either be written in 100% Luau or in 100% PUC Lua 5.1, in order to improve legibility without needless sacrifice of compatibility, and vice versa.

# Motivation
[motivation]: #motivation

The current version of `UNCCheckEnv.lua` contains Luau features such as compound assignment (+=, *=, ..=, etc), but also unfriendly PUC Lua 5.1 idioms such as `a and b or c`. This sacrifices the utility of the script on 2 fronts:

1. Compatibility issues with non Luau executors (if any such UNC compliant executors exist)
2. Sacrifice to code legibility due to PUC Lua 5.1 idioms and lack of type information

This can be corrected by switching to complete conformance with either Luau or PUC Lua 5.1

# Reference-level explanation
[reference-level-explanation]: #reference-level-explanation

The implementation of this feature only affects the conformance checking script, and not the standard itself. As was discused, complete conformance to either Luau or PUC Lua 5.1 is the goal, which would be achieved by converting PUC Lua 5.1 idioms into Luau idioms/features, or vice versa. For example:

This PUC Lua 5.1 idiom:
```lua
local x = switch and a or b
```
Can become:
```lua
local x = if switch then a else b
```
With much better legibility.

The same is true with:
```lua
for key, value in ipairs(table)
```
As it becomes:
```lua
for key, value in table
```
(There initially used to be a performance drawback to the 2nd, but this is no longer the case)

And finally, this is especially important with function prototypes/signatures:
```lua
local function concat(...)
```
Can become:
```lua
local function concat(...: table)
```

# Drawbacks
[drawbacks]: #drawbacks

This may compromise legibility for the sake of compatibility, or vice versa; there is no perfect outcome in this situation, but the maintainers have the final say on what to sacrifice for what.

# Rationale and alternatives
[rationale-and-alternatives]: #rationale-and-alternatives

The only alternative is to do nothing, but taking a decision now is imperative. The UNC is an important standard, and it only makes sense for the conformance checker script to conform to a standard as well, leaving it in limbo is hypocritical and can cause problems for people down the road.

# Prior art
[prior-art]: #prior-art
 
0866 made a contribution that greatly improved the performance and legibility of the script from its initial iteration, but the changes were inadequate and the current iteration remains in limbo.

# Unresolved questions
[unresolved-questions]: #unresolved-questions

The main unresolved question here is if there are any UNC executors without Luau support that would get affected by a change to Luau, or are currently affected by the presence of Luau-only features in the current version of the script.

**Comment by EpixScripts** [comment]
The reason it's using the common "and/or" idiom is that a lot of executors have not adopted support for if expressions.

**Comment by dyslexicsteak** [comment]
> The reason it's using the common "and/or" idiom is that a lot of executors have not adopted support for if expressions.

Understood, closing.
